// Generated by scripts/generate-model-catalog.mjs — DO NOT EDIT.
// Source: https://models.dev/api.json (provider facts only)
// Automated refresh: .github/workflows/update-model-catalog.yml
//
// Facts models.dev publishes per provider: name, docs URL, API root, env keys
// and wire adapter. The channel's model list is MODEL_CATALOG[sourceId] in
// lib/models/catalog.generated.ts (same snapshot). Endpoint variants, dialects,
// per-model protocol rules and local services live in presets.overlay.ts.
import type { CatalogProviderId } from "../../models/catalog.generated";
import type { ProviderChatProtocol } from "./protocols";

export { MODEL_CATALOG_SNAPSHOT_DATE } from "../../models/catalog.generated";

export type GeneratedPreset = {
  id: string;
  /** Catalog section listing this channel's models: MODEL_CATALOG[sourceId]. */
  sourceId: CatalogProviderId;
  name: string;
  doc?: string;
  envKeys: readonly string[];
  adapter: string;
  protocols: readonly ProviderChatProtocol[];
  baseUrl: string;
};

export const GENERATED_PRESETS: readonly GeneratedPreset[] = [
  { id: "anthropic", sourceId: "anthropic", name: "Anthropic", doc: "https://docs.anthropic.com/en/docs/about-claude/models", envKeys: ["ANTHROPIC_API_KEY"], adapter: "@ai-sdk/anthropic", protocols: ["anthropic-messages"], baseUrl: "https://api.anthropic.com/v1" },
  { id: "openai", sourceId: "openai", name: "OpenAI", doc: "https://platform.openai.com/docs/models", envKeys: ["OPENAI_API_KEY"], adapter: "@ai-sdk/openai", protocols: ["openai-responses", "openai-completions"], baseUrl: "https://api.openai.com/v1" },
  { id: "gemini", sourceId: "google", name: "Google", doc: "https://ai.google.dev/gemini-api/docs/models", envKeys: ["GOOGLE_API_KEY", "GOOGLE_GENERATIVE_AI_API_KEY", "GEMINI_API_KEY"], adapter: "@ai-sdk/google", protocols: ["google-generative-ai"], baseUrl: "https://generativelanguage.googleapis.com/v1beta" },
  { id: "xai", sourceId: "xai", name: "xAI", doc: "https://docs.x.ai/docs/models", envKeys: ["XAI_API_KEY"], adapter: "@ai-sdk/xai", protocols: ["openai-responses"], baseUrl: "https://api.x.ai/v1" },
  { id: "deepseek", sourceId: "deepseek", name: "DeepSeek", doc: "https://api-docs.deepseek.com/quick_start/pricing", envKeys: ["DEEPSEEK_API_KEY"], adapter: "@ai-sdk/openai-compatible", protocols: ["openai-completions"], baseUrl: "https://api.deepseek.com" },
  { id: "zhipu", sourceId: "zhipuai", name: "Zhipu AI", doc: "https://docs.z.ai/guides/overview/pricing", envKeys: ["ZHIPU_API_KEY"], adapter: "@ai-sdk/openai-compatible", protocols: ["openai-completions"], baseUrl: "https://open.bigmodel.cn/api/paas/v4" },
  { id: "minimax", sourceId: "minimax", name: "MiniMax (minimax.io)", doc: "https://platform.minimax.io/docs/guides/quickstart", envKeys: ["MINIMAX_API_KEY"], adapter: "@ai-sdk/anthropic", protocols: ["anthropic-messages"], baseUrl: "https://api.minimax.io/anthropic/v1" },
  { id: "minimax-cn", sourceId: "minimax-cn", name: "MiniMax (minimaxi.com)", doc: "https://platform.minimaxi.com/docs/guides/quickstart", envKeys: ["MINIMAX_API_KEY"], adapter: "@ai-sdk/anthropic", protocols: ["anthropic-messages"], baseUrl: "https://api.minimaxi.com/anthropic/v1" },
  { id: "moonshot", sourceId: "moonshotai", name: "Moonshot AI", doc: "https://platform.moonshot.ai/docs/api/chat", envKeys: ["MOONSHOT_API_KEY"], adapter: "@ai-sdk/openai-compatible", protocols: ["openai-completions"], baseUrl: "https://api.moonshot.ai/v1" },
  { id: "moonshot-cn", sourceId: "moonshotai-cn", name: "Moonshot AI (China)", doc: "https://platform.moonshot.cn/docs/api/chat", envKeys: ["MOONSHOT_API_KEY"], adapter: "@ai-sdk/openai-compatible", protocols: ["openai-completions"], baseUrl: "https://api.moonshot.cn/v1" },
  { id: "dashscope", sourceId: "alibaba", name: "Alibaba", doc: "https://www.alibabacloud.com/help/en/model-studio/models", envKeys: ["DASHSCOPE_API_KEY"], adapter: "@ai-sdk/openai-compatible", protocols: ["openai-completions"], baseUrl: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1" },
  { id: "dashscope-cn", sourceId: "alibaba-cn", name: "Alibaba (China)", doc: "https://www.alibabacloud.com/help/en/model-studio/models", envKeys: ["DASHSCOPE_API_KEY"], adapter: "@ai-sdk/openai-compatible", protocols: ["openai-completions"], baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1" },
  { id: "volcengine", sourceId: "volcengine", name: "Volcengine Ark", doc: "https://www.volcengine.com/docs/82379/1330310", envKeys: ["ARK_API_KEY"], adapter: "@ai-sdk/openai-compatible", protocols: ["openai-completions"], baseUrl: "https://ark.cn-beijing.volces.com/api/v3" },
  { id: "siliconflow", sourceId: "siliconflow", name: "SiliconFlow", doc: "https://cloud.siliconflow.com/models", envKeys: ["SILICONFLOW_API_KEY"], adapter: "@ai-sdk/openai-compatible", protocols: ["openai-completions"], baseUrl: "https://api.siliconflow.com/v1" },
  { id: "siliconflow-cn", sourceId: "siliconflow-cn", name: "SiliconFlow (China)", doc: "https://cloud.siliconflow.com/models", envKeys: ["SILICONFLOW_CN_API_KEY"], adapter: "@ai-sdk/openai-compatible", protocols: ["openai-completions"], baseUrl: "https://api.siliconflow.cn/v1" },
  { id: "groq", sourceId: "groq", name: "Groq", doc: "https://console.groq.com/docs/models", envKeys: ["GROQ_API_KEY"], adapter: "@ai-sdk/groq", protocols: ["openai-completions"], baseUrl: "https://api.groq.com/openai/v1" },
  { id: "openrouter", sourceId: "openrouter", name: "OpenRouter", doc: "https://openrouter.ai/models", envKeys: ["OPENROUTER_API_KEY"], adapter: "@openrouter/ai-sdk-provider", protocols: ["openai-completions"], baseUrl: "https://openrouter.ai/api/v1" },
  { id: "lmstudio", sourceId: "lmstudio", name: "LMStudio", doc: "https://lmstudio.ai/models", envKeys: ["LMSTUDIO_API_KEY"], adapter: "@ai-sdk/openai-compatible", protocols: ["openai-completions"], baseUrl: "http://127.0.0.1:1234/v1" },
];
