export const EXTRACTION_CONVERSATION_STATE_LIMIT = 10000;
export const EXTRACTION_WRITTEN_SLUG_LIMIT = 1000;
export const EXTRACTION_CANDIDATE_LIMIT = 50;
export const EXTRACTION_REJECTION_DAYS = 30;
export const EXTRACTION_TIMEOUT_MS = 30000;
