//! Walker：`ignore` crate 遍历（尊重 .gitignore/.ignore）+ 内置排除 + 配额。
//! 增量判定在 service 层结合 store 完成；这里只产出候选文件清单。

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

use ignore::gitignore::{Gitignore, GitignoreBuilder};
use ignore::WalkBuilder;
use sha2::{Digest, Sha256};

/// 单文件上限：超过基本是生成物/数据文件，索引价值低且拖慢嵌入。
pub(crate) const MAX_FILE_BYTES: u64 = 1024 * 1024;
/// 单仓库文件数配额（防止把 home 目录当工作区拖垮机器）。
pub(crate) const MAX_FILES: usize = 50_000;
/// 单仓库源码总量配额。
pub(crate) const MAX_TOTAL_BYTES: u64 = 500 * 1024 * 1024;

/// `ignore` 之外的内置排除目录（.gitignore 缺失/不全时兜底）。
const EXCLUDED_DIRS: &[&str] = &[
    ".git",
    "node_modules",
    "target",
    "dist",
    "build",
    "out",
    ".next",
    ".venv",
    "venv",
    "__pycache__",
    ".cache",
    "vendor",
    "Pods",
];

/// 明确的二进制/媒体扩展名，避免浪费一次 UTF-8 探测读。
/// svg 虽是文本，但内容是路径坐标噪声，实测污染语义路，按媒体处理。
const EXCLUDED_EXTENSIONS: &[&str] = &[
    "png", "jpg", "jpeg", "gif", "webp", "ico", "icns", "bmp", "tiff", "avif", "svg", "mp3", "mp4",
    "mov", "avi", "mkv", "wav", "flac", "ogg", "zip", "tar", "gz", "zst", "br", "7z", "rar", "jar",
    "class", "pyc", "wasm", "so", "dylib", "dll", "exe", "bin", "dat", "pdf", "woff", "woff2",
    "ttf", "otf", "eot", "sqlite", "sqlite3", "db", "lock", "lockb", "min.js", "map",
];

/// 按整名排除的生成物锁文件：`.lock` 扩展名兜不住这些拼法（package-lock.json
/// 是 .json）。实测它们以 JSON 元数据大量挤占语义路 top-k（小工作区里
/// 7 个 package-lock 占掉 11% 的块），检索价值为零。
const EXCLUDED_FILENAMES: &[&str] = &["package-lock.json", "pnpm-lock.yaml", "npm-shrinkwrap.json"];

/// 生成物头部标记（小写比对）。各生态的生成器约定把声明放进文件头几行：
/// Go（`Code generated by … DO NOT EDIT.`）、protobuf/Meta（`@generated`）、
/// Cython（`/* Generated by Cython 0.29.x */`）等。1.1 万行的 Cython 产物
/// 这类文件按扩展名/大小都拦不住，入索引后大量稀释 top-k（评审 #630 条目 4）。
const GENERATED_HEAD_MARKERS: &[&str] = &[
    "@generated",
    "do not edit",
    "do not modify",
    "code generated by",
    "generated by cython",
    "auto-generated",
    "auto generated",
    "autogenerated",
    "automatically generated",
];

/// 生成物/数据 blob 探测：只看头部（前 10 行、每行前 512 字符）找生成器
/// 标记；前 5 行里出现超长行（> 4 KB）视为 minified/数据文件——真实源码
/// 不会一行 4 KB。误判代价是该文件退出语义索引，Grep 仍可兜底检索。
pub(crate) fn looks_generated(content: &str) -> bool {
    let mut head = String::with_capacity(2_048);
    for (index, line) in content.lines().take(10).enumerate() {
        if index < 5 && line.len() > 4_096 {
            return true;
        }
        if head.len() < 2_048 {
            head.extend(line.chars().take(512));
            head.push('\n');
        }
    }
    let head = head.to_lowercase();
    GENERATED_HEAD_MARKERS
        .iter()
        .any(|marker| head.contains(marker))
}

/// 内置排除规则的版本号。改动 EXCLUDED_* 任一清单时 +1：service 检索路
/// 发现索引落后于当前规则会自愈拉起增量 job，靠“消失文件对账”清掉
/// 已入库的新排除物（增量对未变化文件短路，代价只有一次遍历）。
pub(crate) const WALKER_RULES_VERSION: &str = "2";

#[derive(Debug, Clone)]
pub(crate) struct WalkedFile {
    /// workspace 相对路径，POSIX 分隔符。
    pub(crate) rel_path: String,
    pub(crate) abs_path: PathBuf,
    pub(crate) mtime_ms: i64,
    pub(crate) size_bytes: u64,
}

pub(crate) struct WalkOutcome {
    pub(crate) files: Vec<WalkedFile>,
    /// 遍历期间被跳过的出错条目数（不可读目录、瞬时消失等）。非零时清单
    /// 可能不完整，调用方不得据此做“消失文件”删除对账。
    pub(crate) walk_errors: usize,
}

fn extension_excluded(path: &Path) -> bool {
    let name = path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or_default()
        .to_ascii_lowercase();
    if EXCLUDED_FILENAMES.iter().any(|excluded| name == *excluded) {
        return true;
    }
    EXCLUDED_EXTENSIONS
        .iter()
        .any(|ext| name.ends_with(&format!(".{ext}")))
}

pub(crate) fn relativize(workdir: &Path, path: &Path) -> Option<String> {
    let rel = path.strip_prefix(workdir).ok()?;
    let rel = rel.to_string_lossy().replace('\\', "/");
    if rel.is_empty() {
        None
    } else {
        Some(rel)
    }
}

/// 全量遍历。`should_cancel` 为协作式取消探针（jobs 同款）。
pub(crate) fn walk_workspace(
    workdir: &Path,
    should_cancel: &dyn Fn() -> bool,
) -> Result<WalkOutcome, String> {
    // 根目录不可达必须是硬错误：吞掉会得到“空工作区”，触发全量删除对账。
    let root_meta = std::fs::metadata(workdir)
        .map_err(|e| format!("无法访问工作区目录 {}：{e}", workdir.display()))?;
    if !root_meta.is_dir() {
        return Err(format!("工作区路径不是目录：{}", workdir.display()));
    }

    let mut files = Vec::new();
    let mut walk_errors = 0usize;
    let mut total_bytes: u64 = 0;

    let walker = WalkBuilder::new(workdir)
        .hidden(false) // 允许 .github 等点目录进入，靠 EXCLUDED_DIRS 与 gitignore 兜排除
        .git_ignore(true)
        .git_global(true)
        .git_exclude(true)
        // 非 git 目录同样尊重 .gitignore：隐私优先（.env 等约定排除物不进索引），
        // 也与 watch 增量的 WatchPathFilter 行为一致。
        .require_git(false)
        .follow_links(false)
        .filter_entry(|entry| {
            // depth 0 是 workdir 根自身：即使名字撞上排除表（如仓库就叫
            // build）也必须放行，否则整棵树消失。
            if entry.depth() == 0 {
                return true;
            }
            let name = entry.file_name().to_string_lossy();
            !EXCLUDED_DIRS.iter().any(|dir| name == *dir)
        })
        .build();

    for entry in walker {
        if should_cancel() {
            return Err(super::jobs::INDEX_CANCELLED_ERROR.to_string());
        }
        let Ok(entry) = entry else {
            walk_errors += 1;
            continue;
        };
        let Some(file_type) = entry.file_type() else {
            continue;
        };
        if !file_type.is_file() {
            continue;
        }
        let path = entry.path();
        if extension_excluded(path) {
            continue;
        }
        let Ok(metadata) = entry.metadata() else {
            // 文件存在但 stat 失败（瞬时抖动/权限）：必须计入错误——清单缺了
            // 它，若不计数，删除对账会把活文件当“消失”移出索引。
            walk_errors += 1;
            continue;
        };
        let size = metadata.len();
        if size == 0 || size > MAX_FILE_BYTES {
            continue;
        }
        let Some(rel_path) = relativize(workdir, path) else {
            continue;
        };
        let mtime_ms = metadata
            .modified()
            .ok()
            .and_then(|value| value.duration_since(std::time::UNIX_EPOCH).ok())
            .map(|duration| duration.as_millis() as i64)
            .unwrap_or(0);

        total_bytes = total_bytes.saturating_add(size);
        files.push(WalkedFile {
            rel_path,
            abs_path: path.to_path_buf(),
            mtime_ms,
            size_bytes: size,
        });

        if files.len() > MAX_FILES {
            return Err(format!(
                "工作区文件数超过索引配额（{MAX_FILES}）。请用 .gitignore/.ignore 排除生成物目录后重试。"
            ));
        }
        if total_bytes > MAX_TOTAL_BYTES {
            return Err(format!(
                "工作区源码量超过索引配额（{} MiB）。请用 .gitignore/.ignore 排除大目录后重试。",
                MAX_TOTAL_BYTES / (1024 * 1024)
            ));
        }
    }

    Ok(WalkOutcome { files, walk_errors })
}

/// watch 增量路径的排除过滤：与全量遍历同源的规则（内置目录/扩展名 +
/// 根到变更文件各级目录的 .gitignore/.ignore + .git/info/exclude）。
///
/// 取保守语义：任一 matcher 判 ignore 即排除；跨文件的 `!pattern` 白名单
/// 还原不实现——漏索引的文件由下一次全量/增量 job 对账补回，而误索引
/// gitignore 内容（如 .env 密钥）是这里必须堵住的方向。
pub(crate) struct WatchPathFilter {
    workdir: PathBuf,
    /// (matcher 根目录, matcher)。matched_path_or_any_parents 对不在其根下的
    /// 路径会 assert panic，匹配前必须按根前缀筛选。
    matchers: Vec<(PathBuf, Gitignore)>,
    /// 全局 gitignore（core.excludesFile）。其根在用户配置目录，工作区路径
    /// 不在其下，只能走无断言的 `matched()`（按文件与各级祖先目录逐一判）。
    global: Option<Gitignore>,
}

impl WatchPathFilter {
    pub(crate) fn new(workdir: &Path, rel_paths: &BTreeSet<String>) -> Self {
        // 变更路径涉及的目录链：根 + 每个相对路径的所有祖先目录。
        let mut dirs: BTreeSet<PathBuf> = BTreeSet::new();
        dirs.insert(workdir.to_path_buf());
        for rel_path in rel_paths {
            let mut current = workdir.to_path_buf();
            if let Some(parent) = Path::new(rel_path).parent() {
                for component in parent.components() {
                    current = current.join(component);
                    dirs.insert(current.clone());
                }
            }
        }
        // 工作区位于更大仓库内部时，外层目录的 .gitignore 同样约束全量遍历
        //（WalkBuilder parents 默认开启）：向上收集到仓库根（.git 所在层）为止。
        if !workdir.join(".git").exists() {
            let mut above = workdir.parent();
            let mut hops = 0;
            while let Some(dir) = above {
                dirs.insert(dir.to_path_buf());
                if hops >= 16 || dir.join(".git").exists() {
                    break;
                }
                above = dir.parent();
                hops += 1;
            }
        }
        let mut matchers = Vec::new();
        for dir in &dirs {
            for name in [".gitignore", ".ignore"] {
                let ignore_file = dir.join(name);
                if ignore_file.is_file() {
                    let mut builder = GitignoreBuilder::new(dir);
                    builder.add(&ignore_file);
                    if let Ok(matcher) = builder.build() {
                        matchers.push((dir.clone(), matcher));
                    }
                }
            }
        }
        let git_exclude = workdir.join(".git").join("info").join("exclude");
        if git_exclude.is_file() {
            let mut builder = GitignoreBuilder::new(workdir);
            builder.add(&git_exclude);
            if let Ok(matcher) = builder.build() {
                matchers.push((workdir.to_path_buf(), matcher));
            }
        }
        // 全局 gitignore（core.excludesFile）：全量遍历开了 git_global，这里对齐。
        let (global, _error) = Gitignore::global();
        let global = (global.num_ignores() > 0).then_some(global);
        Self {
            workdir: workdir.to_path_buf(),
            matchers,
            global,
        }
    }

    pub(crate) fn allows(&self, rel_path: &str) -> bool {
        if rel_path
            .split('/')
            .any(|segment| EXCLUDED_DIRS.contains(&segment))
        {
            return false;
        }
        if extension_excluded(Path::new(rel_path)) {
            return false;
        }
        let abs = self.workdir.join(rel_path);
        if self.matchers.iter().any(|(root, matcher)| {
            abs.starts_with(root)
                && matcher.matched_path_or_any_parents(&abs, false).is_ignore()
        }) {
            return false;
        }
        if let Some(global) = &self.global {
            // 文件本体 + 工作区内的各级祖先目录逐一判（补齐 dir/ 形态的模式）。
            if global.matched(&abs, false).is_ignore() {
                return false;
            }
            let mut ancestor = abs.parent();
            while let Some(dir) = ancestor {
                if !dir.starts_with(&self.workdir) || dir == self.workdir {
                    break;
                }
                if global.matched(dir, true).is_ignore() {
                    return false;
                }
                ancestor = dir.parent();
            }
        }
        true
    }
}

/// 读文件正文；非 UTF-8（含 BOM 之外的二进制）返回 None 跳过。
pub(crate) fn read_text_file(path: &Path) -> Option<String> {
    let bytes = std::fs::read(path).ok()?;
    String::from_utf8(bytes).ok()
}

pub(crate) fn sha256_hex(input: &[u8]) -> String {
    let digest = Sha256::digest(input);
    digest.iter().map(|byte| format!("{byte:02x}")).collect()
}
