// Generated by scripts/generate-model-catalog.mjs — DO NOT EDIT.
// Source: https://models.dev/api.json (providers: anthropic, google, openai, xai)
// Refresh: make update-model-catalog

export type CatalogModelCostTier = {
  inputTokensAbove: number;
  input: number;
  output: number;
  cacheRead: number;
  cacheWrite: number;
};

export type CatalogModelCost = {
  input: number;
  output: number;
  cacheRead: number;
  cacheWrite: number;
  tiers?: readonly CatalogModelCostTier[];
};

export type CatalogModelEntry = {
  id: string;
  contextWindow: number;
  maxOutputToken: number;
  cost?: CatalogModelCost;
};

export type CatalogProviderId = "anthropic" | "google" | "openai" | "xai";

export const MODEL_CATALOG_SNAPSHOT_DATE = "2026-07-24";

export const MODEL_CATALOG: Record<CatalogProviderId, readonly CatalogModelEntry[]> = {
  anthropic: [
    { id: "claude-fable-5", contextWindow: 1000000, maxOutputToken: 128000, cost: { input: 10, output: 50, cacheRead: 1, cacheWrite: 12.5 } },
    { id: "claude-haiku-4-5", contextWindow: 200000, maxOutputToken: 64000, cost: { input: 1, output: 5, cacheRead: 0.1, cacheWrite: 1.25 } },
    { id: "claude-haiku-4-5-20251001", contextWindow: 200000, maxOutputToken: 64000, cost: { input: 1, output: 5, cacheRead: 0.1, cacheWrite: 1.25 } },
    { id: "claude-opus-4-1", contextWindow: 200000, maxOutputToken: 32000, cost: { input: 15, output: 75, cacheRead: 1.5, cacheWrite: 18.75 } },
    { id: "claude-opus-4-1-20250805", contextWindow: 200000, maxOutputToken: 32000, cost: { input: 15, output: 75, cacheRead: 1.5, cacheWrite: 18.75 } },
    { id: "claude-opus-4-5", contextWindow: 200000, maxOutputToken: 64000, cost: { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 } },
    { id: "claude-opus-4-5-20251101", contextWindow: 200000, maxOutputToken: 64000, cost: { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 } },
    { id: "claude-opus-4-6", contextWindow: 1000000, maxOutputToken: 128000, cost: { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 } },
    { id: "claude-opus-4-7", contextWindow: 1000000, maxOutputToken: 128000, cost: { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 } },
    { id: "claude-opus-4-8", contextWindow: 1000000, maxOutputToken: 128000, cost: { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 } },
    { id: "claude-sonnet-4-5", contextWindow: 1000000, maxOutputToken: 64000, cost: { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 3.75 } },
    { id: "claude-sonnet-4-5-20250929", contextWindow: 1000000, maxOutputToken: 64000, cost: { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 3.75 } },
    { id: "claude-sonnet-4-6", contextWindow: 1000000, maxOutputToken: 128000, cost: { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 3.75 } },
    { id: "claude-sonnet-5", contextWindow: 1000000, maxOutputToken: 128000, cost: { input: 2, output: 10, cacheRead: 0.2, cacheWrite: 2.5 } },
  ],
  google: [
    { id: "deep-research-max-preview-04-2026", contextWindow: 1048576, maxOutputToken: 65536, cost: { input: 2, output: 12, cacheRead: 0.2, cacheWrite: 0, tiers: [{ inputTokensAbove: 200000, input: 4, output: 18, cacheRead: 0.4, cacheWrite: 0 }] } },
    { id: "deep-research-preview-04-2026", contextWindow: 1048576, maxOutputToken: 65536, cost: { input: 2, output: 12, cacheRead: 0.2, cacheWrite: 0, tiers: [{ inputTokensAbove: 200000, input: 4, output: 18, cacheRead: 0.4, cacheWrite: 0 }] } },
    { id: "gemini-2.0-flash", contextWindow: 1048576, maxOutputToken: 8192, cost: { input: 0.1, output: 0.4, cacheRead: 0.025, cacheWrite: 0 } },
    { id: "gemini-2.0-flash-lite", contextWindow: 1048576, maxOutputToken: 8192, cost: { input: 0.075, output: 0.3, cacheRead: 0, cacheWrite: 0 } },
    { id: "gemini-2.5-computer-use-preview-10-2025", contextWindow: 128000, maxOutputToken: 64000, cost: { input: 1.25, output: 10, cacheRead: 0, cacheWrite: 0, tiers: [{ inputTokensAbove: 200000, input: 2.5, output: 15, cacheRead: 0, cacheWrite: 0 }] } },
    { id: "gemini-2.5-flash", contextWindow: 1048576, maxOutputToken: 65536, cost: { input: 0.3, output: 2.5, cacheRead: 0.03, cacheWrite: 0 } },
    { id: "gemini-2.5-flash-image", contextWindow: 32768, maxOutputToken: 8192, cost: { input: 0.3, output: 30, cacheRead: 0.075, cacheWrite: 0 } },
    { id: "gemini-2.5-flash-lite", contextWindow: 1048576, maxOutputToken: 65536, cost: { input: 0.1, output: 0.4, cacheRead: 0.01, cacheWrite: 0 } },
    { id: "gemini-2.5-pro", contextWindow: 1048576, maxOutputToken: 65536, cost: { input: 1.25, output: 10, cacheRead: 0.125, cacheWrite: 0, tiers: [{ inputTokensAbove: 200000, input: 2.5, output: 15, cacheRead: 0.25, cacheWrite: 0 }] } },
    { id: "gemini-3-flash-preview", contextWindow: 1048576, maxOutputToken: 65536, cost: { input: 0.5, output: 3, cacheRead: 0.05, cacheWrite: 0 } },
    { id: "gemini-3-pro-image", contextWindow: 65536, maxOutputToken: 32768, cost: { input: 2, output: 120, cacheRead: 0, cacheWrite: 0 } },
    { id: "gemini-3-pro-image-preview", contextWindow: 131072, maxOutputToken: 32768, cost: { input: 2, output: 120, cacheRead: 0, cacheWrite: 0 } },
    { id: "gemini-3-pro-preview", contextWindow: 1048576, maxOutputToken: 65536, cost: { input: 2, output: 12, cacheRead: 0.2, cacheWrite: 0, tiers: [{ inputTokensAbove: 200000, input: 4, output: 18, cacheRead: 0.4, cacheWrite: 0 }] } },
    { id: "gemini-3.1-flash-image", contextWindow: 131072, maxOutputToken: 32768, cost: { input: 0.5, output: 60, cacheRead: 0, cacheWrite: 0 } },
    { id: "gemini-3.1-flash-image-preview", contextWindow: 65536, maxOutputToken: 16384, cost: { input: 0.5, output: 60, cacheRead: 0, cacheWrite: 0 } },
    { id: "gemini-3.1-flash-lite", contextWindow: 1048576, maxOutputToken: 65536, cost: { input: 0.25, output: 1.5, cacheRead: 0.025, cacheWrite: 0 } },
    { id: "gemini-3.1-flash-lite-image", contextWindow: 65536, maxOutputToken: 4096, cost: { input: 0.25, output: 30, cacheRead: 0, cacheWrite: 0 } },
    { id: "gemini-3.1-flash-lite-preview", contextWindow: 1048576, maxOutputToken: 65536, cost: { input: 0.25, output: 1.5, cacheRead: 0.025, cacheWrite: 0 } },
    { id: "gemini-3.1-flash-live-preview", contextWindow: 131072, maxOutputToken: 65536, cost: { input: 0.75, output: 4.5, cacheRead: 0, cacheWrite: 0 } },
    { id: "gemini-3.1-pro-preview", contextWindow: 1048576, maxOutputToken: 65536, cost: { input: 2, output: 12, cacheRead: 0.2, cacheWrite: 0, tiers: [{ inputTokensAbove: 200000, input: 4, output: 18, cacheRead: 0.4, cacheWrite: 0 }] } },
    { id: "gemini-3.1-pro-preview-customtools", contextWindow: 1048576, maxOutputToken: 65536, cost: { input: 2, output: 12, cacheRead: 0.2, cacheWrite: 0, tiers: [{ inputTokensAbove: 200000, input: 4, output: 18, cacheRead: 0.4, cacheWrite: 0 }] } },
    { id: "gemini-3.5-flash", contextWindow: 1048576, maxOutputToken: 65536, cost: { input: 1.5, output: 9, cacheRead: 0.15, cacheWrite: 0 } },
    { id: "gemini-3.5-flash-lite", contextWindow: 1048576, maxOutputToken: 65536, cost: { input: 0.3, output: 2.5, cacheRead: 0.03, cacheWrite: 0 } },
    { id: "gemini-3.5-live-translate-preview", contextWindow: 131072, maxOutputToken: 65536, cost: { input: 3.5, output: 21, cacheRead: 0, cacheWrite: 0 } },
    { id: "gemini-3.6-flash", contextWindow: 1048576, maxOutputToken: 65536, cost: { input: 1.5, output: 7.5, cacheRead: 0.15, cacheWrite: 0 } },
    { id: "gemini-embedding-001", contextWindow: 2048, maxOutputToken: 1, cost: { input: 0.15, output: 0, cacheRead: 0, cacheWrite: 0 } },
    { id: "gemini-embedding-2", contextWindow: 8192, maxOutputToken: 3072, cost: { input: 0.2, output: 0, cacheRead: 0, cacheWrite: 0 } },
    { id: "gemini-flash-latest", contextWindow: 1048576, maxOutputToken: 65536, cost: { input: 1.5, output: 9, cacheRead: 0.15, cacheWrite: 0 } },
    { id: "gemini-flash-lite-latest", contextWindow: 1048576, maxOutputToken: 65536, cost: { input: 0.25, output: 1.5, cacheRead: 0.025, cacheWrite: 0 } },
    { id: "gemini-robotics-er-1.6-preview", contextWindow: 131072, maxOutputToken: 65536, cost: { input: 1, output: 5, cacheRead: 0, cacheWrite: 0 } },
    { id: "gemma-4-26b-a4b-it", contextWindow: 262144, maxOutputToken: 32768 },
    { id: "gemma-4-31b-it", contextWindow: 262144, maxOutputToken: 32768 },
    { id: "lyria-3-clip-preview", contextWindow: 131072, maxOutputToken: 65536 },
    { id: "lyria-3-pro-preview", contextWindow: 131072, maxOutputToken: 8192 },
  ],
  openai: [
    { id: "gpt-3.5-turbo", contextWindow: 16385, maxOutputToken: 4096, cost: { input: 0.5, output: 1.5, cacheRead: 0, cacheWrite: 0 } },
    { id: "gpt-4", contextWindow: 8192, maxOutputToken: 2048, cost: { input: 30, output: 60, cacheRead: 0, cacheWrite: 0 } },
    { id: "gpt-4-turbo", contextWindow: 128000, maxOutputToken: 4096, cost: { input: 10, output: 30, cacheRead: 0, cacheWrite: 0 } },
    { id: "gpt-4.1", contextWindow: 1047576, maxOutputToken: 32768, cost: { input: 2, output: 8, cacheRead: 0.5, cacheWrite: 0 } },
    { id: "gpt-4.1-mini", contextWindow: 1047576, maxOutputToken: 32768, cost: { input: 0.4, output: 1.6, cacheRead: 0.1, cacheWrite: 0 } },
    { id: "gpt-4.1-nano", contextWindow: 1047576, maxOutputToken: 32768, cost: { input: 0.1, output: 0.4, cacheRead: 0.025, cacheWrite: 0 } },
    { id: "gpt-4o", contextWindow: 128000, maxOutputToken: 16384, cost: { input: 2.5, output: 10, cacheRead: 1.25, cacheWrite: 0 } },
    { id: "gpt-4o-2024-05-13", contextWindow: 128000, maxOutputToken: 4096, cost: { input: 5, output: 15, cacheRead: 0, cacheWrite: 0 } },
    { id: "gpt-4o-2024-08-06", contextWindow: 128000, maxOutputToken: 16384, cost: { input: 2.5, output: 10, cacheRead: 1.25, cacheWrite: 0 } },
    { id: "gpt-4o-2024-11-20", contextWindow: 128000, maxOutputToken: 16384, cost: { input: 2.5, output: 10, cacheRead: 1.25, cacheWrite: 0 } },
    { id: "gpt-4o-mini", contextWindow: 128000, maxOutputToken: 16384, cost: { input: 0.15, output: 0.6, cacheRead: 0.075, cacheWrite: 0 } },
    { id: "gpt-5", contextWindow: 400000, maxOutputToken: 128000, cost: { input: 1.25, output: 10, cacheRead: 0.125, cacheWrite: 0 } },
    { id: "gpt-5-chat-latest", contextWindow: 400000, maxOutputToken: 128000, cost: { input: 1.25, output: 10, cacheRead: 0.125, cacheWrite: 0 } },
    { id: "gpt-5-codex", contextWindow: 400000, maxOutputToken: 128000, cost: { input: 1.25, output: 10, cacheRead: 0.125, cacheWrite: 0 } },
    { id: "gpt-5-mini", contextWindow: 400000, maxOutputToken: 128000, cost: { input: 0.25, output: 2, cacheRead: 0.025, cacheWrite: 0 } },
    { id: "gpt-5-nano", contextWindow: 400000, maxOutputToken: 128000, cost: { input: 0.05, output: 0.4, cacheRead: 0.005, cacheWrite: 0 } },
    { id: "gpt-5-pro", contextWindow: 400000, maxOutputToken: 272000, cost: { input: 15, output: 120, cacheRead: 0, cacheWrite: 0 } },
    { id: "gpt-5.1", contextWindow: 400000, maxOutputToken: 128000, cost: { input: 1.25, output: 10, cacheRead: 0.125, cacheWrite: 0 } },
    { id: "gpt-5.1-chat-latest", contextWindow: 128000, maxOutputToken: 16384, cost: { input: 1.25, output: 10, cacheRead: 0.125, cacheWrite: 0 } },
    { id: "gpt-5.1-codex", contextWindow: 400000, maxOutputToken: 128000, cost: { input: 1.25, output: 10, cacheRead: 0.125, cacheWrite: 0 } },
    { id: "gpt-5.1-codex-max", contextWindow: 400000, maxOutputToken: 128000, cost: { input: 1.25, output: 10, cacheRead: 0.125, cacheWrite: 0 } },
    { id: "gpt-5.1-codex-mini", contextWindow: 400000, maxOutputToken: 128000, cost: { input: 0.25, output: 2, cacheRead: 0.025, cacheWrite: 0 } },
    { id: "gpt-5.2", contextWindow: 400000, maxOutputToken: 128000, cost: { input: 1.75, output: 14, cacheRead: 0.175, cacheWrite: 0 } },
    { id: "gpt-5.2-chat-latest", contextWindow: 128000, maxOutputToken: 16384, cost: { input: 1.75, output: 14, cacheRead: 0.175, cacheWrite: 0 } },
    { id: "gpt-5.2-codex", contextWindow: 400000, maxOutputToken: 128000, cost: { input: 1.75, output: 14, cacheRead: 0.175, cacheWrite: 0 } },
    { id: "gpt-5.2-pro", contextWindow: 400000, maxOutputToken: 128000, cost: { input: 21, output: 168, cacheRead: 0, cacheWrite: 0 } },
    { id: "gpt-5.3-chat-latest", contextWindow: 128000, maxOutputToken: 16384, cost: { input: 1.75, output: 14, cacheRead: 0.175, cacheWrite: 0 } },
    { id: "gpt-5.3-codex", contextWindow: 400000, maxOutputToken: 128000, cost: { input: 1.75, output: 14, cacheRead: 0.175, cacheWrite: 0 } },
    { id: "gpt-5.3-codex-spark", contextWindow: 128000, maxOutputToken: 32000, cost: { input: 1.75, output: 14, cacheRead: 0.175, cacheWrite: 0 } },
    { id: "gpt-5.4", contextWindow: 1050000, maxOutputToken: 128000, cost: { input: 2.5, output: 15, cacheRead: 0.25, cacheWrite: 0, tiers: [{ inputTokensAbove: 272000, input: 5, output: 22.5, cacheRead: 0.5, cacheWrite: 0 }] } },
    { id: "gpt-5.4-mini", contextWindow: 400000, maxOutputToken: 128000, cost: { input: 0.75, output: 4.5, cacheRead: 0.075, cacheWrite: 0 } },
    { id: "gpt-5.4-nano", contextWindow: 400000, maxOutputToken: 128000, cost: { input: 0.2, output: 1.25, cacheRead: 0.02, cacheWrite: 0 } },
    { id: "gpt-5.4-pro", contextWindow: 1050000, maxOutputToken: 128000, cost: { input: 30, output: 180, cacheRead: 0, cacheWrite: 0, tiers: [{ inputTokensAbove: 272000, input: 60, output: 270, cacheRead: 0, cacheWrite: 0 }] } },
    { id: "gpt-5.5", contextWindow: 1050000, maxOutputToken: 128000, cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 0, tiers: [{ inputTokensAbove: 272000, input: 10, output: 45, cacheRead: 1, cacheWrite: 0 }] } },
    { id: "gpt-5.5-pro", contextWindow: 1050000, maxOutputToken: 128000, cost: { input: 30, output: 180, cacheRead: 0, cacheWrite: 0, tiers: [{ inputTokensAbove: 272000, input: 60, output: 270, cacheRead: 0, cacheWrite: 0 }] } },
    { id: "gpt-5.6", contextWindow: 1050000, maxOutputToken: 128000, cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 6.25, tiers: [{ inputTokensAbove: 272000, input: 10, output: 45, cacheRead: 1, cacheWrite: 12.5 }] } },
    { id: "gpt-5.6-luna", contextWindow: 1050000, maxOutputToken: 128000, cost: { input: 1, output: 6, cacheRead: 0.1, cacheWrite: 1.25, tiers: [{ inputTokensAbove: 272000, input: 2, output: 9, cacheRead: 0.2, cacheWrite: 2.5 }] } },
    { id: "gpt-5.6-sol", contextWindow: 1050000, maxOutputToken: 128000, cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 6.25, tiers: [{ inputTokensAbove: 272000, input: 10, output: 45, cacheRead: 1, cacheWrite: 12.5 }] } },
    { id: "gpt-5.6-terra", contextWindow: 1050000, maxOutputToken: 128000, cost: { input: 2.5, output: 15, cacheRead: 0.25, cacheWrite: 3.125, tiers: [{ inputTokensAbove: 272000, input: 5, output: 22.5, cacheRead: 0.5, cacheWrite: 6.25 }] } },
    { id: "gpt-realtime-2.1", contextWindow: 128000, maxOutputToken: 32000, cost: { input: 4, output: 24, cacheRead: 0.4, cacheWrite: 0 } },
    { id: "o1", contextWindow: 200000, maxOutputToken: 100000, cost: { input: 15, output: 60, cacheRead: 7.5, cacheWrite: 0 } },
    { id: "o1-pro", contextWindow: 200000, maxOutputToken: 100000, cost: { input: 150, output: 600, cacheRead: 0, cacheWrite: 0 } },
    { id: "o3", contextWindow: 200000, maxOutputToken: 100000, cost: { input: 2, output: 8, cacheRead: 0.5, cacheWrite: 0 } },
    { id: "o3-deep-research", contextWindow: 200000, maxOutputToken: 100000, cost: { input: 10, output: 40, cacheRead: 2.5, cacheWrite: 0 } },
    { id: "o3-mini", contextWindow: 200000, maxOutputToken: 100000, cost: { input: 1.1, output: 4.4, cacheRead: 0.55, cacheWrite: 0 } },
    { id: "o3-pro", contextWindow: 200000, maxOutputToken: 100000, cost: { input: 20, output: 80, cacheRead: 0, cacheWrite: 0 } },
    { id: "o4-mini", contextWindow: 200000, maxOutputToken: 100000, cost: { input: 1.1, output: 4.4, cacheRead: 0.275, cacheWrite: 0 } },
    { id: "o4-mini-deep-research", contextWindow: 200000, maxOutputToken: 100000, cost: { input: 2, output: 8, cacheRead: 0.5, cacheWrite: 0 } },
    { id: "text-embedding-3-large", contextWindow: 8191, maxOutputToken: 3072, cost: { input: 0.13, output: 0, cacheRead: 0, cacheWrite: 0 } },
    { id: "text-embedding-3-small", contextWindow: 8191, maxOutputToken: 1536, cost: { input: 0.02, output: 0, cacheRead: 0, cacheWrite: 0 } },
    { id: "text-embedding-ada-002", contextWindow: 8192, maxOutputToken: 1536, cost: { input: 0.1, output: 0, cacheRead: 0, cacheWrite: 0 } },
  ],
  xai: [
    { id: "grok-4.20-0309-non-reasoning", contextWindow: 1000000, maxOutputToken: 30000, cost: { input: 1.25, output: 2.5, cacheRead: 0.2, cacheWrite: 0, tiers: [{ inputTokensAbove: 200000, input: 2.5, output: 5, cacheRead: 0.4, cacheWrite: 0 }] } },
    { id: "grok-4.20-0309-reasoning", contextWindow: 1000000, maxOutputToken: 30000, cost: { input: 1.25, output: 2.5, cacheRead: 0.2, cacheWrite: 0, tiers: [{ inputTokensAbove: 200000, input: 2.5, output: 5, cacheRead: 0.4, cacheWrite: 0 }] } },
    { id: "grok-4.20-multi-agent-0309", contextWindow: 1000000, maxOutputToken: 30000, cost: { input: 1.25, output: 2.5, cacheRead: 0.2, cacheWrite: 0, tiers: [{ inputTokensAbove: 200000, input: 2.5, output: 5, cacheRead: 0.4, cacheWrite: 0 }] } },
    { id: "grok-4.3", contextWindow: 1000000, maxOutputToken: 30000, cost: { input: 1.25, output: 2.5, cacheRead: 0.2, cacheWrite: 0, tiers: [{ inputTokensAbove: 200000, input: 2.5, output: 5, cacheRead: 0.4, cacheWrite: 0 }] } },
    { id: "grok-4.5", contextWindow: 500000, maxOutputToken: 32000, cost: { input: 2, output: 6, cacheRead: 0.3, cacheWrite: 0, tiers: [{ inputTokensAbove: 200000, input: 4, output: 12, cacheRead: 1, cacheWrite: 0 }] } },
    { id: "grok-build-0.1", contextWindow: 256000, maxOutputToken: 32000, cost: { input: 1, output: 2, cacheRead: 0.2, cacheWrite: 0, tiers: [{ inputTokensAbove: 200000, input: 2, output: 4, cacheRead: 0.4, cacheWrite: 0 }] } },
  ],
};
